#!/usr/bin/python
"""
blogger-zipper -- make images align to "zipper" style"
In order to zigzag, we need to look for this pattern:
    'div.separator > a > img'
and perform these transformations:
    <a> set style, alternate between these lines:
            style="clear: left;  float: left;  margin-bottom: 1em; margin-right: 1em;"
            style="clear: right; float: right; margin-bottom: 1em; margin-left: 1em;"
    <img> set height="150"
              width="200"

"""

import sys
from bs4 import BeautifulSoup

before="""
<div class="separator" style="clear: both; text-align: center;">
<a href="http://3.bp.blogspot.com/-zLnBfsJh9zE/TVrAMEA5G5I/AAAAAAAAAXw/4nVUGy8oxII/s1600/P1000768.JPG" imageanchor="1" style="clear: left; float: left; margin-bottom: 1em; margin-right: 1em;"><img border="0" src="http://3.bp.blogspot.com/-zLnBfsJh9zE/TVrAMEA5G5I/AAAAAAAAAXw/4nVUGy8oxII/s320/P1000768.JPG" height="150" width="200" /></a></div>

<div class="separator" style="clear: both; text-align: center;">
<a href="http://3.bp.blogspot.com/-HvZgpexyF28/TVrATKLGzyI/AAAAAAAAAX0/1f8Pa0ckIbY/s1600/P1000774.JPG" imageanchor="1" style="clear: right; float: right; margin-bottom: 1em; margin-left: 1em;"><img border="0" src="http://3.bp.blogspot.com/-HvZgpexyF28/TVrATKLGzyI/AAAAAAAAAX0/1f8Pa0ckIbY/s320/P1000774.JPG" height="150" width="200" /></a></div>

<div class="separator" style="clear: both; text-align: center;">
<a href="http://1.bp.blogspot.com/-vOgBLzCjVfM/TVrAY3WWFEI/AAAAAAAAAX4/Q2NGFvN4keM/s1600/P1000788.JPG" imageanchor="1" style="margin-left: 1em; margin-right: 1em;"><img border="0" src="http://1.bp.blogspot.com/-vOgBLzCjVfM/TVrAY3WWFEI/AAAAAAAAAX4/Q2NGFvN4keM/s320/P1000788.JPG" height="240" width="320" /></a></div>

<div class="separator" style="clear: both; text-align: center;">
<a href="http://4.bp.blogspot.com/-OZfbQVLizy8/TVrAeBpK9oI/AAAAAAAAAX8/L3w79eCfUOs/s1600/P1000789.JPG" imageanchor="1" style="margin-left: 1em; margin-right: 1em;"><img border="0" src="http://4.bp.blogspot.com/-OZfbQVLizy8/TVrAeBpK9oI/AAAAAAAAAX8/L3w79eCfUOs/s320/P1000789.JPG" height="240" width="320" /></a></div>

<div class="separator" style="clear: both; text-align: center;">
<a href="http://3.bp.blogspot.com/-fZRYAy2xR_I/TVrAkNiDkfI/AAAAAAAAAYA/kZwzKUrm6l0/s1600/P1000790.JPG" imageanchor="1" style="margin-left: 1em; margin-right: 1em;"><img border="0" src="http://3.bp.blogspot.com/-fZRYAy2xR_I/TVrAkNiDkfI/AAAAAAAAAYA/kZwzKUrm6l0/s320/P1000790.JPG" height="240" width="320" /></a></div>
"""
before=sys.stdin.read()

soup = BeautifulSoup(before)

dirix=1
dirs=(("left","left","right"),("right","right","left"))
astyle='clear: %s; float: %s; margin-bottom: 1em; margin-%s: 1em;'

for i in soup.select('div.separator > a > img'):
   s=astyle%dirs[dirix]
   dirix=1-dirix
   i.parent['style']=s
   i['height']='150'
   i['width']='200'

print soup.prettify()
